<strong>Pridobivanje novega gesla</strong>
<p>To sporočilo si prejel, ker si potožil, da si izgubil geslo. Nič hudega to se zgodi tudi najboljšim.
<p>Novo geslo si boš lahko izbral, če boš sledil linku <a href="http://stejem.si/uporabnik/novogeslo/id/<?php echo $this->id; ?>/token/<?php echo $this->token?>" title="Naj te ne bo strah, nič hudega ne bo!">tukaj</a></p>
<p>Lep pozdrav<br />stejem.si admin</p>