<form method="post" accept-charset="UTF-8" action="<?php echo $this->url(array('controller' => 'delo', 'action' => 'addclearance'))?>" enctype="application/x-www-form-urlencoded">    
<table>

<tr>
    <th class="last" ><input type="checkbox" id="checkAll" title="Izberi vse" checked="checked" /></th>
    <th>Datum</th>
    <th>Služba</th>
    <th>Tarifa</th>
    <th>Ura prihoda</th>
    <th>Ura odhoda</th>
    <th>Čas dela</th>

    <th>Zaslužek</th>
    <th class="last"></th>
</tr>
<?php
$tmpId = $this->work[0]['id_job'];
$seconds = 0;
$earnings = 0;
foreach($this->work as $dela) : ?>

    <?php
     if($tmpId !== $dela['id_job']) : ?>
    <tr class="last">
	<td colspan="6" class="left"></td>

        <td class="vsota">Σ: <?php echo sprintf( "%02.2d:%02.2d", floor( $seconds / 3600 ), floor(($seconds % 3600)/60)); ?></td>
        <td class="vsota right">Σ: <?php echo $this->currencyFormat($earnings) ?></td>
    </tr>
    <?php $seconds = 0; $earnings = 0; $tmpId = $dela['id_job']; endif; 


     $seconds += $dela['seconds'];
     $earnings += $dela['earnings'];

    ?>

<tr>

    <td class="left"><input type="checkbox" name="stat[]" value="<?php echo $dela['id'];?>" checked="checked" class="check"  /></td>
    <td title="<?php echo ($dela['date_added']);?>"><?php echo $this->dateFormat($dela['date']);?></td>
    <td><?php echo ($dela['name']);?></td>
    <td class="right"><?php echo $this->currencyFormat($dela['wage']);?></td>
    <td><?php echo $this->timeFormat($dela['start_time']);?></td>
    <td><?php echo $this->timeFormat($dela['end_time']);?></td>
    <td><?php echo $this->timeFormat($dela['difference']);?></td>

    <td class="right"><?php echo $this->currencyFormat($dela['earnings']);?></td>

    <td><a href="<?php echo $this->url(array('controller'=>'delo',
            'action'=>'uredi', 'id'=>$dela['id']));?>" class="uredi" title="Uredi"></a><a href="<?php echo $this->url(array('controller'=>'delo',
            'action'=>'deletework', 'id'=>$dela['id']));?>"  class="zbrisi" title="Izbriši"></a></td>
</tr>
<?php endforeach; ?>

<tr class="last">
    <td colspan="6" class="left"><input type="submit" value="Obračunaj izbrane" /></td>

    <td class="vsota">Σ: <?php printf( "%02.2d:%02.2d", floor( $seconds / 3600 ), floor(($seconds % 3600)/60));?></td>
    <td class="vsota right">Σ: <?php echo $this->currencyFormat($earnings) ?></td>
</tr>
</table>
</form>
