
<table>

<tr>
    <th>Datum obračuna</th>
    <th>Od</th>
    <th>Do</th>
    <th>Čas dela</th>
    <th>Zaslužek</th>
    <th class="last"></th>
</tr>
<?php foreach($this->clearance as $clear) : ?>
<tr>

    <td><?php echo $this->dateFormat($clear['date_cleared']);?></td>
    <td><?php echo $this->dateFormat($clear['date_start']);?></td>
    <td><?php echo $this->dateFormat($clear['date_end']);?></td>
    <td><?php echo substr($clear['sum_work'], 0, -3);?></td>
    <td><?php echo $this->currencyFormat($clear['sum_earnings']);?></td>
    <td><a href="<?php echo $this->url(array('controller'=>'delo',
            'action'=>'deleteclearance', 'id'=>$clear['id']));?>"  class="zbrisi"></a></td>
</tr>
<?php endforeach; ?>
<tr class="last">
    <td colspan="2" class="left"></td>
    <td></td>
    <td class="vsota">ΣΣ: <?php echo ($this->sum_clearance) ?></td>
    <td class="vsota">ΣΣ: <?php echo $this->currencyFormat($this->sum_earnings) ?></td>
</tr>
</table>